program: training/forgetmi_loku.py
method: random
parameters:
  project:
    value: "forget_exp"
  entity:
    value: "unlearning"
  use_noise:
    value: false
  do_train:
    value: true
  overwrite_output_dir:
    value: true
  do_eval:
    value: false
  base_model_path:
    value: "./forgetme/training_original_model"
  random_point_ratio:
    value: 0.1
  validation_ratio:
    value: 0.1
  retrained_model_path:
    value: "./model_retrained_3per/"
  output_dir:
    value: "./unlearning_output/"
  bert_pretrained_dir:
    value: "./forgetme/training_original_model/"
  text_data_dir:
    value: "./data/metadata"
  data_split_path:
    value: "./data_splits/mimic-cxr-sub-img-edema-split-manualtest.csv"
  img_data_dir:
    value: "./data/img_data"
  synonyms_dir:
    value: "./data_splits/Synonyms.csv"
  forget_set_path:
    value: "./data_splits/forget_set_3per.csv"
  max_seq_length:
    value: 320
  text_noise_level:
    value: 0.5  
  random_seed:
    value: 42
  output_channel_encoding:
    value: "multiclass"  
  learning_rate:
    values: [1e-4, 1e-5]
  weight_decay:
    value: 0.01
  unlearn_epochs:
    value: 30
  scheduler:
    value: "ReduceLROnPlateau"
  warmup_proportion:
    value: 0.1
  eval_batch_size:
    value: 16
  unlearn_batch_size:
    value: 16
  noise_mean:
    value: 0
  noise_std:
    value: 0.1
  alpha:
    value: 1
  beta:
    value: 1  
  theta:
    value: 2 
  gamma:
    value: 2 
  lora_r:
    value: 8
  lora_alpha:
    value: 16
  lora_dropout:
    value: 0.05
  ihl_margin:
    value: 0.5
  bert_pool_last_hidden: 
    value: false 
  bert_pool_use_img: 
    value: false 
  bert_pool_img_lowerlevel: 
    value: false 
  reprocess_input_data:
    value: false
  id: 
    value: "example"
  use_text_data_dir: 
    value: false
  use_data_split_path: 
    value: false 
  training_mode: 
    value: "supervised"
  semisupervised_training_data: 
    value: "allCXR"
  use_masked_txt: 
    value: false
  use_all_data: 
    value: false
  use_all_data: 
    value: false
  use_pretrained_checkpoint: 
    value: false
  print_predictions: 
    value: false
  print_embeddings: 
    value: false
  num_cpu_workers: 
    value: 8
  logging_steps: 
    value: 50 
  save_epochs: 
    value: 1 
command:
  - ${env:PYTHON}
  - training/forgetmi_loku.py
  - --config=config.yaml

